### ISSUE TITLE
AttributeError: 'mod_wsgi.Input' object has no attribute 'tell'

### ISSUE THREAD

**Issue by sakshigupta3** [googleapis/google-resumable-media-python#123]
I'm running the below versions of httpd, mod_wsgi and latest google-cloud-storage code

- httpd-2.4.41-12.fc31.x86_64
- python3-mod_wsgi-4.6.6-2.fc31.x86_64
-  python3.7

I'm getting the below traceback sometimes,  the issue is intermittent and that's why more confusing ( Like once in an hour ). We upgraded from python2.7 to python3.7, could this be a dependency issue ? Is so, why is it intermittent ? 

 [2020-03-19 07:23:01,337] [ERROR] GCPStorage: PutRequest: stest.2020-03-19/DynamicPolicyRouteChangeTest.py-stest131.sjc-16045647-403435829.log.gz. Unexpected error: (<class 'AttributeError'>) 'mod_wsgi.\
Input' object has no attribute 'tell'
 [2020-03-19 07:23:01,340] [ERROR] Traceback (most recent call last):
   File "/usr/lib/python3.7/site-packages/LogLake/Server.py", line 477, in handlePutRequest
     requestBody, requestHeaders )
   File "/usr/lib/python3.7/site-packages/LogLake/Storage.py", line 79, in putObject
     self.bucketName( bucketName ), objectName, content, headers )
   File "/usr/lib/python3.7/site-packages/LogLake/GCPStorage.py", line 221, in doPutObject
     size=fileSize, client=self.gcpStorageClient )
   File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1261, in upload_from_file
     client, file_obj, content_type, size, num_retries, predefined_acl
   File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1171, in _do_upload
     client, stream, content_type, size, num_retries, predefined_acl
   File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1114, in _do_resumable_upload
     predefined_acl=predefined_acl,
   File "/usr/local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1063, in _initiate_resumable_upload
     stream_final=False,
   File "/usr/local/lib/python3.7/site-packages/google/resumable_media/requests/upload.py", line 343, in initiate
     stream_final=stream_final,
   File "/usr/local/lib/python3.7/site-packages/google/resumable_media/_upload.py", line 414, in _prepare_initiate_request
     if stream.tell() != 0:
 AttributeError: 'mod_wsgi.Input' object has no attribute 'tell'

**Comment by sakshigupta3** [comment]
I raised this issue in mod_wsgi repo and https://github.com/GrahamDumpleton/mod_wsgi/issues/545 the fix helped. FYI: We were running absolutely fine with python2.7.

**Comment by busunkim96** [comment]
@tseaver @crwilcox Could you take a look?

**Comment by IlyaFaer** [comment]
@busunkim96, @crwilcox, I've taken a look, it seems to be not a Resumable Media issue. `upload()` treats an uploaded object as a file-like instance, so it expects an uploaded object to support file methods, like `tell()`, `seek()`, etc.

The object caused the error is not a standard Python, nor Resumable Media object, it's a class from a [third-party package](https://github.com/GrahamDumpleton/mod_wsgi), and it's not very file-like. It supports some of the file operations, but `tell()` and `seek()` are not among them, per [package owner's comment](https://github.com/GrahamDumpleton/mod_wsgi/issues/545#issuecomment-601059199) they can break the expected behavior. Still, user can convert the data from this object into more file-like form and pass it into Res Media's `upload()`.

Thus, there is just no straight way to pass data from the third-party package to Res Media, as both of them have some data requirements, which can't be ignored in any of them. But this can be solved with a data conversion in between them, so I assume the issue can be closed.
