### ISSUE TITLE
Socket timeout

### ISSUE THREAD

**Issue by HamnahMalik** [googleapis/google-resumable-media-python#213]
I am using Resumable upload to upload my hdf file of size around 6-7 GB on GCP Bucket. An d when it50% to 60%  chunks are uploaded I receive the socket timeout error.  Following is the exact error: Code file is attached:
[UploadDataset.docx](https://github.com/googleapis/google-resumable-media-python/files/6404737/UploadDataset.docx)

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.googleapis.com', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/SobiaMalik/PycharmProjectss/gcp-storage/Upload_Dataset.py", line 69, in <module>
    response = upload.transmit_next_chunk(transport)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/resumable_media/requests/upload.py", line 496, in transmit_next_chunk
    response = _request_helpers.http_request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/resumable_media/requests/_request_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/resumable_media/_helpers.py", line 175, in wait_and_retry
    response = func()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/google/auth/transport/requests.py", line 482, in request
    response = super(AuthorizedSession, self).request(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.googleapis.com', port=443): Read timed out. (read timeout=60)

Process finished with exit code 1

**Comment by frankyn** [comment]
Hi @HamnahMalik, thanks for filing the issue!

Could you please share the code inline within your comment?

**Comment by HamnahMalik** [comment]
Yeah sure:

try:
    from google.cloud import storage
    import google.cloud.storage
    import json
    import os
    import sys
    import io
    from io import BytesIO
    import google.resumable_media
    from google.resumable_media.requests import ResumableUpload
    import google.auth
    import google.auth.transport.requests as tr_requests
    from json import JSONEncoder
    import json
    from google.auth.transport.requests import AuthorizedSession
    from google.resumable_media import requests, common
    from google.oauth2 import service_account
    import google.oauth2 as go
    import base64
    import pickle as pickle
    from google.resumable_media.requests import SimpleUpload
    from google.resumable_media.requests import _request_helpers
    from PIL import Image
except Exception as e:
    print("Error : {} ".format(e))

PATH = os.path.join(os.getcwd(),'credentials.json')
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = PATH

storage_client = storage.Client.from_service_account_json(PATH)

ro_scope = u'https://www.googleapis.com/auth/devstorage.read_write'

credentials, _ = google.auth.default(scopes=(ro_scope,))
# create bucket
bucket = storage_client.get_bucket("hamna-bucket")
filename = "%s/%s" % (" ","train_melvsnonmel.hdf5")
train_melvsnonmel = bucket.blob(filename)

url_template = (
     u'https://www.googleapis.com/upload/storage/v1/b/{bucket}/o?'
     u'uploadType=resumable')
upload_url = url_template.format(bucket='hamna-bucket')
transport = tr_requests.AuthorizedSession(credentials)
chunk_size = 5 * (1024 * 1024)  # 5MB

upload = ResumableUpload(upload_url, chunk_size)

with open('train_melvsnonmel.hdf5', 'rb') as f:
    a = f.read()
stream = io.BytesIO(a)

data = a
content_type = 'application/x-hdf;subtype=bag'
metadata = {u'name': 'train_melvsnonmel'}
response = upload.initiate(transport, stream, metadata, content_type,timeout=(_request_helpers._DEFAULT_CONNECT_TIMEOUT,_request_helpers._DEFAULT_READ_TIMEOUT))
print(response)

i=1
while not upload.finished:
    response = upload.transmit_next_chunk(transport)
    i = i+1
    print(i)
    print(response)

**Comment by cojenco** [comment]
Hi @HamnahMalik , thanks for sharing your code within the comments! Could you let us know more about your internet connection and the environment you’re running in? 

The timeout argument can be passed as a tuple (connect_timeout, read_timeout). Currently the default read timeout is 60 seconds. While we were unable to reproduce this on our side, the read_timeout can be altered and is working as expected.

**Comment by cojenco** [comment]
@HamnahMalik, please reopen if you're still facing this issue.
