### ISSUE TITLE
Fix broken docs build

### ISSUE THREAD

**Issue by crwilcox** [googleapis/google-resumable-media-python#55]
`nox -s docs` is failing.

**Comment by tseaver** [comment]
```bash
$ nox -re docs
nox > Running session docs
nox > Re-using existing virtualenv at /home/tseaver/projects/agendaless/Google/src/google-resumable-media-python/.nox/docs.
nox > cd /home/tseaver/projects/agendaless/Google/src/google-resumable-media-python
nox > pip install --upgrade sphinx sphinx_rtd_theme sphinx-docstring-typing >= 0.0.3 requests >= 2.18.0, < 3.0.0dev
nox > pip install --upgrade -e .
nox > bash scripts/build_docs.sh
nox > Warning: bash is not installed into the virtualenv, is it located at /bin/bash. This might cause issues! Pass external=True into run() to silence this message.
Creating file docs_build/google.rst.
Creating file docs_build/google.resumable_media.common.rst.
Creating file docs_build/google.resumable_media.rst.
Creating file docs_build/google.resumable_media.requests.download.rst.
Creating file docs_build/google.resumable_media.requests.upload.rst.
Creating file docs_build/google.resumable_media.requests.rst.
Creating file docs_build/modules.rst.
Traceback (most recent call last):
  File "scripts/rewrite_index_rst.py", line 165, in <module>
    main()
  File "scripts/rewrite_index_rst.py", line 106, in main
    raise ValueError('Unexpected title content', lines[0])
ValueError: ('Unexpected title content', 'google.resumable\\_media package')
```
